### ISSUE TITLE
Request: Remove global directories other than soundfonts/samples

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#10]
Hello again,

I like to keep all my files in project-specific directories. For example, if I'm working on a song called foo, my directory structure would look like this

/data/foo
/data/foo/foo.konfytproject
/data/foo/patches

By using this approach, I can keep my DAW's session file in that directory as well as any other pieces. The idea being that directory contains all the goods required to work on that particular project.

As you know, Konfyt takes a different approach and assumes the user wants all their projects and related patches in a global directory. I've been working around that by leaving "Projects directory" empty in Settings, pressing Cancel at each startup, and then saving my work on a case by case basis. When doing so, I need to skip the "No defaults project directory has been set..." information dialog.

Would it be possible to remove Projects and Patches from the Settings menu so the dialog box doesn't continue to render during each startup and the informational dialog can be avoided? My desired workflow would go something like this:

1. Start Konfyt
2. Work
3. Save the project to a location I specify (knowing a "patches" directory will be created in that location)
4. Profit

Thanks in advance

**Comment by noedigcode** [comment]
I will change it to have a default directory for patches and projects (i.e. not empty by default) so that the dialog doesn't bug you when you don't enter paths for Projects and Patches.

Note that you can still save projects in the location you choose, even when a directory is set up for Projects. The Projects directory is merely the default path to save to when the user doesn't want to specify a path.

Note that the Patches directory, as set in the settings dialog, is where patches are saved when they are added to the library. This is not the path for patches in projects. For each project, the patches in that project are saved with the project.

**Comment by windowsrefund** [comment]
Awesome. One less dialog box to skip. The world is a better place :)

**Comment by noedigcode** [comment]
Newest commit on testing branch now assigns defaults to all paths if not specified and the settings dialog will not continuously be shown anymore if some are not specified.
