### ISSUE TITLE
SFZs are not browsable

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#11]
Either that, or I'm misunderstanding something. I can duplicate the following both with Virtual Playing Orchestra 3.1.2 and [the latest release](https://github.com/sgossner/VSCO-2-CE/releases/tag/1.1.0) of VSCO-CE-2

Konfyt can detect the sfz files and as seen in the screenshot, I can browse/select them. However, I can't seem to access or select any of the instruments contained within each. Instead, I see the actual contents of the .sfz file in the lower left window.

https://imgur.com/i8WdPF7.png

What should my expectations be when attempting to use sfz files from within Konfyt? It seems like sifting through .sfz files directly defeats the point of benefiting from meta information? I'll take a look at this from a carla perspective as well just to see what I see but wanted to get this conversation started.

Also, I'm running from testing branch.

All the best,

**Comment by noedigcode** [comment]
SFZ files do not contain multiple programs/presets/instruments like SF2 (soundfont) files. A single SFZ file corresponds to a single instrument. While a SFZ file might have different sounds for different zones on the keyboard, or keyswitches which alter the sound/instrument, the SFZ file is still seen as a single instrument by the sample loader.

Konfyt does not try to interpret the contents of a SFZ file. It sees it as a single instrument. The implementation of a SFZ file can differ on how the creator decided to implement it. Often you have to read documentation supplied with the SFZ or look for comments inside the SFZ file to know how it is to be used. For convenience, Konfyt displays the contents of the SFZ file to the user since it may contain comments from the creator or other clues as to how the instrument is to be used.

**Comment by windowsrefund** [comment]
oh... ok, now I know. Thank you.
