### ISSUE TITLE
Support or SF4/SF3?

### ISSUE THREAD

**Issue by mxmilkiib** [noedigcode/konfyt#18]
SF4 being FLAC and SF3 being Vorbis.

See also https://github.com/cognitone/sf2convert

**Comment by noedigcode** [comment]
The latest commits on the testing branch added support for SF3. Since Fluidsynth already supports SF3, it was a quick fix - simply allowing files with the .sf3 extension to be detected and loaded.
Since Fluidsynth doesn't support SF4 (and it's not standard yet), it's unlikely that I will add support for it. Does anything use/plan to use SF4 yet?
